### ISSUE TITLE
Links dos Blogs quebrados

### ISSUE THREAD

**Issue by lucassmacedo** [geiltonxavier/aprenda-go#15]
Olá! nenhum dos links dos Blogs estão em funcionamento mais.

**Comment by geiltonxavier** [comment]
@lucassmacedo poxa :( realmente man, acabei de atualizar o blog do Avelino, os demais não achei...
se você tiver algum blog para indicar, fiique a vontade para abrir um PR.

**Comment by geiltonxavier** [comment]
link atualizado.
