### ISSUE TITLE
Reestruturação de repositório

### ISSUE THREAD

**Issue by rafa-acioly** [geiltonxavier/aprenda-go#9]
Gostei bastante da idéia do repositório pois já faz algum tempo que procuro conteudo a respeito do `Go`, porém listar todos os recursos em um arquivo de texto pode ser dificil de organizar e até mesmo de encontrar algo, por isso gostaria de propor o uso da organização do repositório [awesome-br](https://github.com/awesome-br/awesome-br.github.io), que cria cards para organização geral dos conteudos.

O que acham?

**Comment by geiltonxavier** [comment]
@rafa-acioly achei bem legal esse projeto, ainda não conhecia.

Referente a reestruturação, eu não acredito que vá crescer tanto assim como as listas awesome-xx, mas pode ser uma opção.
O que você acha @zeucxb ?

**Comment by zeucxb** [comment]
Acho que de awesome tem o do avelino awesome-go e abordar tanta coisa assim não é o propósito.

Eliseu Codinhoto (@zeucxb)

**Comment by rafa-acioly** [comment]
a questão é separar e organizar melhor o repositório e não criar um "novo awesome" para go, é mais questão de organização e facilidade de encontrar os conteúdos.

**Comment by geiltonxavier** [comment]
@rafa-acioly eu entendi a sua sugestão de separação, mas acredito que essa lista não vá crescer tanto assim por ser bem específico da linguagem, e a ideia aqui é colocar o melhor conteúdo relevante para quem vai iniciar em Go.
Mas sua sugestão é válida, e pode vir a ser uma opção.

**Comment by zeucxb** [comment]
Concordo com o @geiltonxavier, é uma boa opção, mas acredito que o objetivo não seja ter esse tamanho.
